#! /bin/sh

sxhkd &
yabar &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap           0

##Color settings
bspc config normal_frame_opacity 1.0
bspc config focused_frame_opacity 0.05
bspc config focused_border_color "#99CC99"
bspc config normal_border_color "#000000"
bspc config border_width 5
bspc config split_ratio 0.52

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium
